title: My portfolio
email: tommaso.vaccari@mail.polimi.it
description: >- # this means to ignore newlines until "baseurl:"
  Tommaso Vaccari's Portfolio
baseurl: "" # the subpath of your site, e.g. /blog
url: "tommasovaccari.com" # the base hostname & protocol for your site, e.g. http://example.com

github_username:  T-vaccari
highlighter: rouge

# Build settings
theme: minima
plugins:
  - jekyll-feed
permalink: /:categories/:year/:month/:day/:title.html

collections:
  posts:
    output: true

# Exclude from processing.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
